if: (branch = develop) OR (branch = master) OR (type = pull_request) OR (tag IS present)

dist: xenial

language: node_js

node_js:
- '9'

cache:
  directories:
    - node_modules

before_install:
  - apt-get install zip

before_deploy:
  - ./ci/build_production_releases.sh

deploy:
  provider: releases
  api_key: "${GITHUB_API_KEY}"
  file_glob: true
  file:
    - ci/outputs/*-rinkeby.zip
    - ci/outputs/*-mainnet.zip
  skip_cleanup: true
  draft: true
  #on:
  #  tags: true
